#User config params
#obs and act spaces
num_actions: 12
num_observations: 43
num_stacks: 3

control_dt: 0.015

#joint position increments limits
act_inc_high: [ 3.5,  15. ] # f*2+(leg*5)*2+torso*1+(arm*4)*2
act_inc_low: [ 0.5, -15. ]

#target command ranges
vx_cmd_range: [ -0.3, 0.5 ] #m/s
yr_cmd_range: [ -1., 1. ]  #rad/s
kp_yaw_ctrl: 2.

#reference joint action
sin_joint_idx: 1
use_sim_gait: false
ref_joint_act: [ 0.330302, 0.317694, 0.900974, 1.23461, 0.715731,      0.323668, -0.0274747, -0.0328365, 0.180606, -0.0646634 ] #Standing Mode Joint Positions
#ref_joint_act:[ RL_HIP_YAW, RL_HIP_ROLL, RL_HIP_PITCH, RL_KNEE,  RL_ANKLE,     LL_HIP_YAW, LL_HIP_ROLL, LL_HIP_PITCH,  LL_KNEE,    LL_ANKLE]

#joint position limits
act_pos_low:  [ -1, -1, -1, -1, -1,      -1, -1, -1, -1, -1 ] # Legs to rear : Right to Left
act_pos_high: [ 2, 2, 2, 2, 2,      2, 2, 2, 2, 2 ] # Legs to front : Right to Left

#motor stiffness and damping
# for soft control
kp_soft: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ] #(hip*3+knee*1+ankle*1)*2
kd_soft: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ] #(hip*3+knee*1+ankle*1)*2

# for position stand and rl control
kp: [ 1, 0.5, 1.5, 1, 1, 1, 0.5, 1.5, 1, 1 ] #(hip*3+knee*1+ankle*1)*2
kd: [ 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05 ] #(hip*3+knee*1+ankle*1)*2